### ISSUE TITLE
error in create database

### ISSUE THREAD

**Issue by MohMehrnia** [FusionAuth/fusionauth-site#2821]
Hello,
When in maintenance mode I click on the submit button shows an error message, i use nginx for reverse proxy
`2024-01-17 05:57:19.448 PM INFO  c.inversoft.maintenance.action.MaintenanceModeDatabaseConfigurationAction - [3] Request an update to the database status using root credentials.
2024-01-17 05:57:19.547 PM ERROR c.inversoft.maintenance.action.MaintenanceModeDatabaseConfigurationAction - Unexpected error is ORDINARY_USER_MISSING_PRIVS
2024-01-17 05:57:19.549 PM ERROR org.primeframework.mvc.workflow.DefaultExceptionHandler - Unhandled exception occurred
org.primeframework.mvc.message.l10n.MissingMessageException: Message could not be found for the URI [/maintenance-mode-database-configuration] and key [[ORDINARY_USER_MISSING_PRIVS]]
	at org.primeframework.mvc.message.l10n.ResourceBundleMessageProvider.getMessage(ResourceBundleMessageProvider.java:79)
	at com.inversoft.maintenance.action.BaseMaintenanceModeAction.addGeneralError(BaseMaintenanceModeAction.java:60)
	at com.inversoft.maintenance.action.MaintenanceModeDatabaseConfigurationAction.post(MaintenanceModeDatabaseConfigurationAction.java:141)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.primeframework.mvc.util.ReflectionUtils.invoke(ReflectionUtils.java:443)
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.execute(DefaultActionInvocationWorkflow.java:77)
	at org.primeframework.mvc.action.DefaultActionInvocationWorkflow.perform(DefaultActionInvocationWorkflow.java:60)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:50)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.validation.DefaultValidationWorkflow.perform(DefaultValidationWorkflow.java:45)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.security.DefaultSecurityWorkflow.perform(DefaultSecurityWorkflow.java:60)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.parameter.DefaultPostParameterWorkflow.perform(DefaultPostParameterWorkflow.java:49)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.content.DefaultContentWorkflow.perform(DefaultContentWorkflow.java:74)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:58)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:92)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:50)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:119)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:65)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at com.inversoft.maintenance.primeframework.MaintenanceModePrimeWorkflow.perform(MaintenanceModePrimeWorkflow.java:49)
	at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:50)
	at com.inversoft.maintenance.primeframework.mvc.MaintenanceModeMVCWorkflow.perform(MaintenanceModeMVCWorkflow.java:96)
	at org.primeframework.mvc.PrimeMVCRequestHandler.handle(PrimeMVCRequestHandler.java:73)
	at io.fusionauth.http.server.HTTPWorker.run(HTTPWorker.java:50)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by mooreds** [comment]
Hi @MohMehrnia .

Thanks for opening this issue. Please provide more information such as:

* what installation method did you use
* were you using a quickstart and if so which one
* what database do you use
* what version of FusionAuth are you using

I suspect you ran into https://github.com/FusionAuth/fusionauth-issues/issues/2264 but am not certain.

**Comment by mooreds** [comment]
What version is your postgresql database?

**Comment by MohMehrnia** [comment]
14.0

**Comment by mooreds** [comment]
For now, I'd work around it by creating the fusionauth user manually in your PG database and then running the database scripts you can find here: https://fusionauth.io/direct-download

That should allow you to keep moving forward with FusionAuth.

Will raise this issue with the eng team.
